[UPDATE] change read.me 's project info
PoCInnovation/DagViz pull request #6
Opened 2022-04-20 08:54 UTC by Doozers

# Description

Please provide a detailed description of what was done in this PR.
Precise the issue that you are resolving.

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Breaking changes

Please complete this section if any breaking changes have been made, otherwise delete it.

# Checklist

- [ ] I have assigned this PR to myself
- [ ] I have added at least 1 reviewer
- [ ] I have added the needed labels
- [ ] I have linked this PR to an issue
- [ ] I have linked this PR to a milestone
- [ ] I have linked this PR to a project
- [ ] I have tested this code
- [ ] I have added / updated tests (unit / functionals / end-to-end / ...)
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

# Additional comments

Please post additional comments in this section if you have them, otherwise delete it.

2022-04-20 09:07 UTC, TomChv reviewed
Nice, I left 1 comment for one missing information

2022-04-20 09:07 UTC, TomChv commented on README.md
> +| [<img src="https://github.com/MrZalTy.png?size=85" width=85><br><sub>[Ismaël FALL]</sub>](https://github.com/MrZalTy) | [<img src="https://github.com/MrZalTy.png?size=85" width=85><br><sub>[Develop
What about other members of the team?

2022-04-20 09:26 UTC, adrienfort requested changes
Some changes need to be done :+1: Check my comments

Also please **do not put your GitHub username in the name pour the branch** : you should have called it something like `fix/documents`.

Moreover, your PR must resolve an issue. This issue is #1 . Please link this PR to this issue.
As you can see, this issue mention the `CONTRIBUTING.md`. This PR has to fix it too.

2022-04-20 09:26 UTC, adrienfort commented on README.md
> +| [<img src="https://github.com/MrZalTy.png?size=85" width=85><br><sub>[Ismaël FALL]</sub>](https://github.com/MrZalTy) | [<img src="https://github.com/MrZalTy.png?size=85" width=85><br><sub>[Develop
Moreover you can remove the `[` and `]` around the developers's name
Update the links and the pictures too

Here is an [example](https://github.com/PoCInnovation/InterPlanetaryCloud#our-poc-team-ok_hand)

2022-04-20 09:26 UTC, adrienfort commented on README.md
You can remove this
```suggestion
```

2022-04-20 09:27 UTC, adrienfort commented on README.md
> +| [<img src="https://github.com/MrZalTy.png?size=85" width=85><br><sub>[Ismaël FALL]</sub>](https://github.com/MrZalTy) | [<img src="https://github.com/MrZalTy.png?size=85" width=85><br><sub>[Develop
I think you've fixed it just before I submitted my review

2022-04-20 09:40 UTC, Doozers commented on README.md
> +| [<img src="https://github.com/MrZalTy.png?size=85" width=85><br><sub>[Ismaël FALL]</sub>](https://github.com/MrZalTy) | [<img src="https://github.com/MrZalTy.png?size=85" width=85><br><sub>[Develop
I didn't know but Florian did it

2022-04-20 09:41 UTC, Doozers commented on README.md
done :+1:

2022-04-20 09:44 UTC, adrienfort commented
@Doozers can you follow the commits norm explained in the [CONTRIBUTING.md](https://github.com/PoCInnovation/DagViz/blob/main/CONTRIBUTING.md) ?

2022-04-20 09:45 UTC, Doozers commented
> Some changes need to be done +1 Check my comments
> 
> Also please **do not put your GitHub username in the name pour the branch** : you should have called it something like `fix/documents`.
> 
> Moreover, your PR must resolve an issue. This issue is #1 . Please link this PR to this issue. As you can see, this issue mention the `CONTRIBUTING.md`. This PR has to fix it too.

Yes, didn't find the section on the right but it's fix now

2022-04-20 10:20 UTC, adrienfort commented
@Doozers @EdenComp Before merging this PR, have you played on your own with the PoC's project template ?
As mention in the issue #1

2022-04-21 16:36 UTC, adrienfort approved these changes
LGTM

2022-04-21 16:40 UTC, merged